version: '3'
services:
  frontend:
    build: ./frontend/tu-du
    ports:
      - "3000:3000"
    environment:
       - CHOKIDAR_USEPOLLING=true
  backend:
    build: ./backend
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/tudu
      SPRING_DATASOURCE_USERNAME: tudu
      SPRING_DATASOURCE_PASSWORD: tudu123
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: tudu
      MYSQL_USER: tudu
      MYSQL_PASSWORD: tudu123
      MYSQL_ROOT_PASSWORD: root123
    ports:
      - "3307:3306"
